### ISSUE TITLE
Mangrove leaves, roots, propagules, etc. not being compostable (Forge)

### ISSUE THREAD

**Issue by GodzillaFan13** [ItsBlackGear/TheWildBackport-Master#1]
simply what it says on the tin; when in combination with other mods, Mangrove parts that are supposed to be compostable don't compost.

**Comment by ItsBlackGear** [comment]
can you list down the mods that you're currently using? i've checked on the latest version and i am able to compost leaves, roots and propagules on forge.

provide the mod list to see if i'm able to replicate the issue

**Comment by GodzillaFan13** [comment]
![Screenshot (1585)](https://user-images.githubusercontent.com/112220126/187568392-9a7bcc16-c99e-4217-98ce-a07d446073ee.png)

**Comment by Jukabofy** [comment]
They are currently compostable 🤔

**Comment by ItsBlackGear** [comment]
did you update the mod?

**Comment by ItsBlackGear** [comment]
because you're still using 1.2.1 which had some issues related to composting, even if it was fixed on fabric, it works as well on forge so try updating

**Comment by Jukabofy** [comment]
I have almost the same mods as you @GodzillaFan13 
You have to update the mod and check if Quark is messing again

**Comment by GodzillaFan13** [comment]
alright, that fixed it. thanks 👍

**Comment by ItsBlackGear** [comment]
glad to hear that it works! have fun!
