### ISSUE TITLE
Locate commands not working

### ISSUE THREAD

**Issue by Khalelyk** [ItsBlackGear/TheWildBackport-Master#4]
tried looking through both locate and locate biome command, also used key words like deep, dark, skulk.. no results

**Comment by ItsBlackGear** [comment]
To locate modded biomes you need to use the mod id, otherwise it will only look for vanilla biomes
example: `wildbackport:deep_dark`

and the deep dark only generates below y0 so you must go down there to use the locate biome correctly, it's a vanilla issue.

**Comment by ItsBlackGear** [comment]
To locate modded biomes you need to use the mod id, otherwise it will only
look for vanilla biomes

example: wildbackport:deep_dark

And the deep dark only generates below y0 so you must go down there to use
the locate biome correctly, it's a vanilla issue
