### ISSUE TITLE
[Fabric & Forge] Server time out (watchdog crash) issue when visiting a certain chunk. (pillager outpost most likely).

### ISSUE THREAD

**Issue by Gbergz** [ItsBlackGear/TheWildBackport-Master#5]
Title ^

I've been struggling all day trying to find what mod causes a watchdog crash that is currently plaguing my modpack when visiting certain chunks(?).

At first I wasn't sure what chunks caused it and if it was random or not, but after a lot of of binary searching, removing one mod after another it came down to this one causing server to instantly freeze then the watchdog killing it after my set max-tick-time to 900 seconds.

And I think the crash happens whenever I visit a Vanilla [Pillager Outpost](https://minecraft.fandom.com/wiki/Pillager_Outpost). 
And yes it was happening every time I visited one, or came close to it.

I wasn't sure at first what could cause it since the mod doesn't modify anything in the outpost.. I thought. 
Then it hit me that the Allay mob should be able to spawn in the cages there if that feature is backported ofcourse, and that MIGHT has something to do with this watchdog crash.

Edit: This crash happens on both Fabric & Forge.

**Versions:**
Minecraft: 1.18.2
Forge: 40.1.73
Fabric: 0.14.9
Fabric API: 0.58.0
Wild Backport: 1.2.2 | https://www.curseforge.com/minecraft/mc-mods/the-wild-backport/files/3954951 (Fabric)
Wild Backport: 1.2.2 | https://www.curseforge.com/minecraft/mc-mods/the-wild-backport/files/3954946 (Forge)

**Crash-Report**:
https://gist.github.com/Gbergz/3180f8ce5f60a84e19470f09849560c9

The seed it is happening on:
`-6451697684161192220`

teleport to this area and move around to the south ish.
`/tp 819 94 -4`

After removing the mod, going there, letting chunks generate it is a Pillager Outpost very closeby.

Edit: The issue is reproducable with just Wild Backport, Terrablender. In Both Forge & Fabric.
Singleplayer & in multiplayer.

Thanks, 
**-** Gbergz

**Comment by ItsBlackGear** [comment]
oh no, not this again ; - ;

**Comment by ItsBlackGear** [comment]
my current recommendation is to set the max-tick-time to -1 (that would disable it) but it's not a long term solution, just in the meantime as i fix this

**Comment by Gbergz** [comment]
Setting max tick time to -1 has already been tried, it just stalls server and lets it sit there for hours.
Rolling back to version 1.2.1 however solves the issue.

**Comment by ItsBlackGear** [comment]
fixed in 1.2.3
